### ISSUE TITLE
Does not account for non-default idAttribute name

### ISSUE THREAD

**Issue by Shanks512** [seegno/bookshelf-cascade-delete#11]
The plugin throws an error:

``` javascript
Unhandled rejection TypeError: Cannot read property 'toString' of undefined
    at Function.recursiveDeletes (/home/project/node_modules/bookshelf-cascade-delete/dist/index.js:91:113)
    at cascadeDelete (/home/project/node_modules/bookshelf-cascade-delete/dist/index.js:42:54)
```

Probably because it doesn't account for non-default idAttribute values like 'post_id' instead of 'id'

**Comment by ricardogama** [comment]
@Shanks512 Thanks for the tip, released [1.0.2](https://github.com/seegno/bookshelf-cascade-delete/releases/tag/1.0.2) with a fix for this issue, cheers!
